### ISSUE TITLE
value_template not working on Chrome

### ISSUE THREAD

**Issue by tiwek** [denysdovhan/vacuum-card#685]
[X] I updated to the latest version available
[X] I cleared the cache of my browser

on the vacuum-card in the stats -> default section i try to display time in hours instead seconds:

- entity_id: sensor.roborock_vacuum_a38_filter_left
   value_template: '{{ ( value | int * 0.000277778 ) | round }}'
   unit: h
   subtitle: Filtr

Chrome browser show value 244529

![image](https://github.com/denysdovhan/vacuum-card/assets/74269691/949374a3-5f17-4100-b35f-7528ed7b4664)

Firefox, Android show correct value: 68

![image](https://github.com/denysdovhan/vacuum-card/assets/74269691/4b8c42e2-19d1-4026-9479-f7c050fbc396)

- Release: [ 2.8.0]
- Browser: [chrome 120.0.6099.71]
- HomeAssistant version: [2024.1.5]

**Comment by krzywy1121** [comment]
Same here - value_template seems to not work at all

**Comment by Teezy80** [comment]
I have same problem with any web browser.

**Comment by rustyk123** [comment]
I too have this issue in firefox and companion app on iphone and ipad.  however if the value template is used with attribute it works fine, if it is a entity id specifically a sensor with a number value, then it defaults to the value of the entity, and any template for converting the seconds to hours or even minutes will not change that value.

**Comment by tiwek** [comment]
> I too have this issue in firefox and companion app on iphone and ipad. however if the value template is used with attribute it works fine, if it is a entity id specifically a sensor with a number value, then it defaults to the value of the entity, and any template for converting the seconds to hours or even minutes will not change that value.

Yes, but attribute is in seconds :(

**Comment by rustyk123** [comment]
> > I too have this issue in firefox and companion app on iphone and ipad. however if the value template is used with attribute it works fine, if it is a entity id specifically a sensor with a number value, then it defaults to the value of the entity, and any template for converting the seconds to hours or even minutes will not change that value.
> 
> Yes, but attribute is in seconds :(

correct, so is my sensor, my vacuum does not put my filter and brush life timer in an attribute, but in a sensor, my run time is in a attribute, I can use the value template on the run time (attribute) to convert seconds to hours, but my filter and brush life timer I can not use the exact same value template as they are sensors.  but I can take the logic from the value template and put it in a template sensor and it will calculate the hours from seconds and then I can use that template sensor value in the vacuum card, however I don't want a bunch of template sensors created to fix a problem that should be fixed in the add in.

**Comment by r0bb10** [comment]
same here, since i use valetudo the 4 values (main filter, main brush, side brush, sensor) are a separate sensor with a numerical value (in seconds) as state and not an attribute, using value_template does not convert to hours and the workaround is using template sensors but it's not a clean solution.

**Comment by xenotaph** [comment]
Same problem here, can't get it to work.

**Comment by andrein** [comment]
This is still an issue with the latest chrome. HA iOS app displays the values correctly.

**Comment by wepster** [comment]
I'm having similar problem on androit tablet with Fully Kiosk Browser.
On first enter of the dashboard value_template is applied correctly, after some time it becomes large number of seconds :)
This issue is not stale, it needs to be addressed.

**Comment by blob810** [comment]
I have the same issue on Safari and Mac OS Companion App.

**Comment by VMsanity** [comment]
Still not working correctly.. Adding to keep from going stale again

**Comment by zagi988** [comment]
Not only that but when you use value_template it doesn't update the value on screen when the value updates. You need to refresh the page for it to update.

**Comment by goooseman** [comment]
I also face the same issue with template being applied on the initial render, but being broken after state being updated. I believe the bug is in this repo: https://github.com/denysdovhan/ha-template

**Comment by ThatTallGuy21** [comment]
Per the suggestion of others, I created a bunch of template sensors, and when using those I didn't have a problem with the state of the vacuum changes. It refreshes as expected.

![image](https://github.com/user-attachments/assets/740d571a-816c-433f-8a7d-6c84318405df)
